import { buttonSizes, inputSizes, spacing, fontSize, zIndex } from './src/tokens/index.js';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './.storybook/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // line-clamp 類別
    { pattern: /line-clamp-(1[0-9]|[1-9])/ },
    // 常用的網格寬度類別
    'w-1/12',
    'w-2/12',
    'w-3/12',
    'w-4/12',
    'w-5/12',
    'w-6/12',
    'w-7/12',
    'w-8/12',
    'w-9/12',
    'w-10/12',
    'w-11/12',
    'w-full',
    // 響應式寬度 (完整的 1-12)
    'sm:w-1/12',
    'sm:w-2/12',
    'sm:w-3/12',
    'sm:w-4/12',
    'sm:w-5/12',
    'sm:w-6/12',
    'sm:w-7/12',
    'sm:w-8/12',
    'sm:w-9/12',
    'sm:w-10/12',
    'sm:w-11/12',
    'sm:w-full',
    'md:w-1/12',
    'md:w-2/12',
    'md:w-3/12',
    'md:w-4/12',
    'md:w-5/12',
    'md:w-6/12',
    'md:w-7/12',
    'md:w-8/12',
    'md:w-9/12',
    'md:w-10/12',
    'md:w-11/12',
    'md:w-full',
    'lg:w-1/12',
    'lg:w-2/12',
    'lg:w-3/12',
    'lg:w-4/12',
    'lg:w-5/12',
    'lg:w-6/12',
    'lg:w-7/12',
    'lg:w-8/12',
    'lg:w-9/12',
    'lg:w-10/12',
    'lg:w-11/12',
    'lg:w-full',
    'xl:w-1/12',
    'xl:w-2/12',
    'xl:w-3/12',
    'xl:w-4/12',
    'xl:w-5/12',
    'xl:w-6/12',
    'xl:w-7/12',
    'xl:w-8/12',
    'xl:w-9/12',
    'xl:w-10/12',
    'xl:w-11/12',
    'xl:w-full',
    '2xl:w-1/12',
    '2xl:w-2/12',
    '2xl:w-3/12',
    '2xl:w-4/12',
    '2xl:w-5/12',
    '2xl:w-6/12',
    '2xl:w-7/12',
    '2xl:w-8/12',
    '2xl:w-9/12',
    '2xl:w-10/12',
    '2xl:w-11/12',
    '2xl:w-full',
    // 順序類別
    'order-1',
    'order-2',
    'order-3',
    'order-4',
    'order-5',
    'order-6',
    'sm:order-1',
    'sm:order-2',
    'sm:order-3',
    'md:order-1',
    'md:order-2',
    'md:order-3',
    'lg:order-1',
    'lg:order-2',
    'lg:order-3',
    'xl:order-1',
    'xl:order-2',
    'xl:order-3',
    // 基本 flex 和間距類別
    'flex',
    'flex-auto',
    'flex-shrink-0',
    'flex-wrap',
    'flex-nowrap',
    'gap-0',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-5',
    'gap-6',
    'gap-8',
    'gap-10',
    'gap-12',
    'items-start',
    'items-center',
    'items-end',
    'items-stretch',
    'justify-start',
    'justify-center',
    'justify-end',
    'justify-between',
    'justify-around',
    'justify-evenly',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-full',
    'max-w-none',
    'mx-auto',
  ],
  theme: {
    extend: {
      // 擴展 lineClamp 主題以支援更多數值
      lineClamp: {
        7: '7',
        8: '8',
        9: '9',
        10: '10',
        11: '11',
        12: '12',
        13: '13',
        14: '14',
        15: '15',
        16: '16',
        17: '17',
        18: '18',
        19: '19',
        20: '20',
      },
      // 使用 CSS 變數的圓角定義
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        circle: 'var(--radius-circle)',
      },

      // 使用 CSS 變數的顏色定義
      colors: {
        // 品牌色系 - 使用 CSS 變數
        primary: {
          light: 'var(--color-primary-light)',
          DEFAULT: 'var(--color-primary)',
          dark: 'var(--color-primary-dark)',
        },
        secondary: {
          light: 'var(--color-secondary-light)',
          DEFAULT: 'var(--color-secondary)',
          dark: 'var(--color-secondary-dark)',
        },
        info: {
          light: 'var(--color-info-light)',
          DEFAULT: 'var(--color-info)',
          dark: 'var(--color-info-dark)',
        },
        success: {
          light: 'var(--color-success-light)',
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
        },
        warning: {
          light: 'var(--color-warning-light)',
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
        },
        error: {
          light: 'var(--color-error-light)',
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
        },
        // 中性色系 - 使用 CSS 變數
        gray: {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
        },
      },

      // 使用設計系統的間距定義
      spacing,

      // 使用設計系統的字體大小定義
      fontSize,

      // 使用 CSS 變數的陰影定義
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'none',
      },

      // 使用設計系統的層級定義
      zIndex,

      // 按鈕特定的尺寸定義（可用於自定義 utilities）
      buttonSizes,

      // 輸入框特定的尺寸定義
      inputSizes,

      // 動畫與過渡
      animation: {
        'fade-in': 'fadeIn 0.15s ease-in-out',
        'fade-out': 'fadeOut 0.15s ease-in-out',
        'scale-in': 'scaleIn 0.15s ease-in-out',
        'scale-out': 'scaleOut 0.15s ease-in-out',
        'slide-down': 'slideDown 0.15s ease-in-out',
        'slide-up': 'slideUp 0.15s ease-in-out',
      },

      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  // 核心插件配置
  corePlugins: {
    preflight: true,
  },
  plugins: [],
};
