import { buttonSizes, inputSizes, spacing, fontSize, zIndex } from './src/tokens/index.js';

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './.storybook/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    // line-clamp 類別
    { pattern: /line-clamp-(1[0-9]|[1-9])/ },
    // 常用的網格寬度類別
    'w-1/12',
    'w-2/12',
    'w-3/12',
    'w-4/12',
    'w-5/12',
    'w-6/12',
    'w-7/12',
    'w-8/12',
    'w-9/12',
    'w-10/12',
    'w-11/12',
    'w-full',
    // 響應式寬度 (完整的 1-12)
    'sm:w-1/12',
    'sm:w-2/12',
    'sm:w-3/12',
    'sm:w-4/12',
    'sm:w-5/12',
    'sm:w-6/12',
    'sm:w-7/12',
    'sm:w-8/12',
    'sm:w-9/12',
    'sm:w-10/12',
    'sm:w-11/12',
    'sm:w-full',
    'md:w-1/12',
    'md:w-2/12',
    'md:w-3/12',
    'md:w-4/12',
    'md:w-5/12',
    'md:w-6/12',
    'md:w-7/12',
    'md:w-8/12',
    'md:w-9/12',
    'md:w-10/12',
    'md:w-11/12',
    'md:w-full',
    'lg:w-1/12',
    'lg:w-2/12',
    'lg:w-3/12',
    'lg:w-4/12',
    'lg:w-5/12',
    'lg:w-6/12',
    'lg:w-7/12',
    'lg:w-8/12',
    'lg:w-9/12',
    'lg:w-10/12',
    'lg:w-11/12',
    'lg:w-full',
    'xl:w-1/12',
    'xl:w-2/12',
    'xl:w-3/12',
    'xl:w-4/12',
    'xl:w-5/12',
    'xl:w-6/12',
    'xl:w-7/12',
    'xl:w-8/12',
    'xl:w-9/12',
    'xl:w-10/12',
    'xl:w-11/12',
    'xl:w-full',
    '2xl:w-1/12',
    '2xl:w-2/12',
    '2xl:w-3/12',
    '2xl:w-4/12',
    '2xl:w-5/12',
    '2xl:w-6/12',
    '2xl:w-7/12',
    '2xl:w-8/12',
    '2xl:w-9/12',
    '2xl:w-10/12',
    '2xl:w-11/12',
    '2xl:w-full',
    // 順序類別
    'order-1',
    'order-2',
    'order-3',
    'order-4',
    'order-5',
    'order-6',
    'sm:order-1',
    'sm:order-2',
    'sm:order-3',
    'md:order-1',
    'md:order-2',
    'md:order-3',
    'lg:order-1',
    'lg:order-2',
    'lg:order-3',
    'xl:order-1',
    'xl:order-2',
    'xl:order-3',
    // 基本 flex 和間距類別
    'flex',
    'flex-auto',
    'flex-shrink-0',
    'flex-wrap',
    'flex-nowrap',
    'gap-0',
    'gap-1',
    'gap-2',
    'gap-3',
    'gap-4',
    'gap-5',
    'gap-6',
    'gap-8',
    'gap-10',
    'gap-12',
    'items-start',
    'items-center',
    'items-end',
    'items-stretch',
    'justify-start',
    'justify-center',
    'justify-end',
    'justify-between',
    'justify-around',
    'justify-evenly',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-full',
    'max-w-none',
    'mx-auto',
    // 色階相關樣式 - Primary
    'bg-primary-50',
    'bg-primary-100',
    'bg-primary-200',
    'bg-primary-500',
    'bg-primary-600',
    'text-primary-50',
    'text-primary-500',
    'text-primary-600',
    'text-primary-700',
    'text-primary-900',
    'border-primary-200',
    'border-primary-300',
    'border-primary-600',
    // 色階相關樣式 - Secondary
    'bg-secondary-50',
    'bg-secondary-100',
    'bg-secondary-600',
    'text-secondary-500',
    'text-secondary-600',
    'text-secondary-700',
    'text-secondary-900',
    'border-secondary-200',
    'border-secondary-600',
    // 色階相關樣式 - Success
    'bg-success-50',
    'bg-success-100',
    'bg-success-600',
    'text-success-500',
    'text-success-600',
    'text-success-700',
    'text-success-900',
    'border-success-200',
    'border-success-600',
    // 色階相關樣式 - Warning
    'bg-warning-50',
    'bg-warning-100',
    'bg-warning-600',
    'text-warning-500',
    'text-warning-600',
    'text-warning-700',
    'text-warning-900',
    'border-warning-200',
    'border-warning-600',
    // 色階相關樣式 - Error
    'bg-error-50',
    'bg-error-100',
    'bg-error-600',
    'text-error-500',
    'text-error-600',
    'text-error-700',
    'text-error-900',
    'border-error-200',
    'border-error-600',
    // 色階相關樣式 - Info
    'bg-info-50',
    'bg-info-600',
    'bg-info-700',
    'text-info-500',
    'text-info-600',
    'text-info-700',
    'text-info-900',
    'border-info-200',
    // 色階相關樣式 - Gray
    'bg-gray-50',
    'bg-gray-600',
    'bg-gray-700',
    'text-gray-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-900',
    'border-gray-200',
    // Focus ring 樣式
    'focus:ring-primary-500',
    'focus:ring-secondary-500',
    'focus:ring-success-500',
    'focus:ring-warning-500',
    'focus:ring-error-500',
    'focus:ring-info-500',
    'focus:ring-gray-500',
    // 邊框樣式
    'border-l-2',
    'border-2',
  ],
  theme: {
    extend: {
      // 擴展 lineClamp 主題以支援更多數值
      lineClamp: {
        7: '7',
        8: '8',
        9: '9',
        10: '10',
        11: '11',
        12: '12',
        13: '13',
        14: '14',
        15: '15',
        16: '16',
        17: '17',
        18: '18',
        19: '19',
        20: '20',
      },
      // 使用 CSS 變數的圓角定義
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        circle: 'var(--radius-circle)',
      },

      // 使用 CSS 變數的顏色定義
      colors: {
        // Primary 品牌主色 - 完整色階
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
          // 保留向後兼容的命名
          light: 'var(--color-primary-light)',
          DEFAULT: 'var(--color-primary)',
          dark: 'var(--color-primary-dark)',
        },
        // Secondary 輔助色 - 完整色階
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
          // 保留向後兼容的命名
          light: 'var(--color-secondary-light)',
          DEFAULT: 'var(--color-secondary)',
          dark: 'var(--color-secondary-dark)',
        },
        // Info 資訊色 - 完整色階
        info: {
          50: 'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
          800: 'var(--color-info-800)',
          900: 'var(--color-info-900)',
          950: 'var(--color-info-950)',
          // 保留向後兼容的命名
          light: 'var(--color-info-light)',
          DEFAULT: 'var(--color-info)',
          dark: 'var(--color-info-dark)',
        },
        // Success 成功色 - 完整色階
        success: {
          50: 'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          950: 'var(--color-success-950)',
          // 保留向後兼容的命名
          light: 'var(--color-success-light)',
          DEFAULT: 'var(--color-success)',
          dark: 'var(--color-success-dark)',
        },
        // Warning 警告色 - 完整色階
        warning: {
          50: 'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          950: 'var(--color-warning-950)',
          // 保留向後兼容的命名
          light: 'var(--color-warning-light)',
          DEFAULT: 'var(--color-warning)',
          dark: 'var(--color-warning-dark)',
        },
        // Error 錯誤色 - 完整色階
        error: {
          50: 'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
          950: 'var(--color-error-950)',
          // 保留向後兼容的命名
          light: 'var(--color-error-light)',
          DEFAULT: 'var(--color-error)',
          dark: 'var(--color-error-dark)',
        },
        // 中性色系 - 使用 CSS 變數
        gray: {
          50: 'var(--color-gray-50)',
          100: 'var(--color-gray-100)',
          200: 'var(--color-gray-200)',
          300: 'var(--color-gray-300)',
          400: 'var(--color-gray-400)',
          500: 'var(--color-gray-500)',
          600: 'var(--color-gray-600)',
          700: 'var(--color-gray-700)',
          800: 'var(--color-gray-800)',
          900: 'var(--color-gray-900)',
          950: 'var(--color-gray-950)',
        },
      },

      // 使用設計系統的間距定義
      spacing,

      // 使用設計系統的字體大小定義
      fontSize,

      // 使用 CSS 變數的陰影定義
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none: 'none',
      },

      // 使用設計系統的層級定義
      zIndex,

      // 按鈕特定的尺寸定義（可用於自定義 utilities）
      buttonSizes,

      // 輸入框特定的尺寸定義
      inputSizes,

      // 動畫與過渡
      animation: {
        'fade-in': 'fadeIn 0.15s ease-in-out',
        'fade-out': 'fadeOut 0.15s ease-in-out',
        'scale-in': 'scaleIn 0.15s ease-in-out',
        'scale-out': 'scaleOut 0.15s ease-in-out',
        'slide-down': 'slideDown 0.15s ease-in-out',
        'slide-up': 'slideUp 0.15s ease-in-out',
      },

      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        scaleOut: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.95)', opacity: '0' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  // 核心插件配置
  corePlugins: {
    preflight: true,
  },
  plugins: [],
};
